version: "3.7"
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_CUSTOM_EXTENSIONS=/data/custom-nodes/dist
    volumes:
      - D:/GIT/Artifex/N8N/n8n-nodes-pdfco:/data/custom-nodes
